FINDING_LABELS={"ATELECTASIS":"무기폐","CARDIOMEGALY":"심장 비대","CONSOLIDATION":"경화","EDEMA":"폐부종","PLEURAL_EFFUSION":"흉수","PNEUMONIA":"폐렴 의심 소견","PNEUMOTHORAX":"기흉 의심 소견","FRACTURE":"골절 의심 소견","LUNG_OPACITY":"폐 음영 증가","SUPPORT_DEVICES":"의료 장치"}
DEFAULT_THRESHOLDS={code:0.5 for code in FINDING_LABELS}
