"""integrated xray analysis tables"""
from alembic import op
import sqlalchemy as sa
revision="0007_integrated_xray";down_revision="0006_responsible_ai";branch_labels=None;depends_on=None
def upgrade():
    op.create_table("xray_analyses",sa.Column("id",sa.String(36),primary_key=True),sa.Column("anonymous_hash",sa.String(64),nullable=False),sa.Column("modality",sa.String(16),nullable=False),sa.Column("is_dicom",sa.Boolean(),nullable=False),sa.Column("quality",sa.JSON(),nullable=False),sa.Column("region_result",sa.JSON(),nullable=False),sa.Column("screening_status",sa.String(40),nullable=False),sa.Column("uncertainty",sa.JSON(),nullable=False),sa.Column("routing",sa.JSON(),nullable=False),sa.Column("model_info",sa.JSON(),nullable=False),sa.Column("reviewed",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False));op.create_index("ix_xray_analyses_anonymous_hash","xray_analyses",["anonymous_hash"]);op.create_index("ix_xray_analyses_screening_status","xray_analyses",["screening_status"])
    op.create_table("finding_predictions",sa.Column("id",sa.String(36),primary_key=True),sa.Column("analysis_id",sa.String(36),nullable=False),sa.Column("code",sa.String(64),nullable=False),sa.Column("display_name",sa.String(100),nullable=False),sa.Column("probability",sa.Float(),nullable=False),sa.Column("threshold",sa.Float(),nullable=False),sa.Column("positive",sa.Boolean(),nullable=False));op.create_index("ix_finding_predictions_analysis_id","finding_predictions",["analysis_id"])
    op.create_table("explanation_artifacts",sa.Column("id",sa.String(36),primary_key=True),sa.Column("analysis_id",sa.String(36),nullable=False),sa.Column("artifact_type",sa.String(32),nullable=False),sa.Column("storage_uri",sa.String(500),nullable=True),sa.Column("available",sa.Boolean(),nullable=False));op.create_index("ix_explanation_artifacts_analysis_id","explanation_artifacts",["analysis_id"])
    op.create_table("clinical_reviews",sa.Column("id",sa.String(36),primary_key=True),sa.Column("analysis_id",sa.String(36),nullable=False),sa.Column("reviewer_role",sa.String(32),nullable=False),sa.Column("final_region",sa.String(32),nullable=False),sa.Column("final_findings",sa.JSON(),nullable=False),sa.Column("comment",sa.Text(),nullable=False),sa.Column("before_value",sa.JSON(),nullable=False),sa.Column("after_value",sa.JSON(),nullable=False),sa.Column("audit_event_id",sa.String(36),nullable=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False));op.create_index("ix_clinical_reviews_analysis_id","clinical_reviews",["analysis_id"])
    op.create_table("model_registry",sa.Column("id",sa.String(36),primary_key=True),sa.Column("model_name",sa.String(100),nullable=False),sa.Column("model_version",sa.String(64),nullable=False),sa.Column("checkpoint_hash",sa.String(64),nullable=True),sa.Column("dummy_mode",sa.Boolean(),nullable=False),sa.Column("approval_status",sa.String(32),nullable=False));op.create_index("ix_model_registry_model_name","model_registry",["model_name"]);op.create_index("ix_model_registry_model_version","model_registry",["model_version"])
def downgrade():
    for table in ("model_registry","clinical_reviews","explanation_artifacts","finding_predictions","xray_analyses"):op.drop_table(table)
