"""institution operations and model release gate"""
from alembic import op
import sqlalchemy as sa
revision="0009_operations";down_revision="0008_longitudinal";branch_labels=None;depends_on=None
def upgrade():
    op.create_table("study_analyses",sa.Column("id",sa.String(36),primary_key=True),sa.Column("study_id",sa.String(36),nullable=False),sa.Column("instance_results",sa.JSON(),nullable=False),sa.Column("aggregate_result",sa.JSON(),nullable=False),sa.Column("clinical_context",sa.JSON(),nullable=False),sa.Column("clinical_context_effect",sa.JSON(),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("priority_reasons",sa.JSON(),nullable=False),sa.Column("priority_rule_version",sa.String(32),nullable=False),sa.Column("reviewed",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("review_priority_rules",sa.Column("id",sa.String(36),primary_key=True),sa.Column("version",sa.String(32),nullable=False,unique=True),sa.Column("thresholds",sa.JSON(),nullable=False),sa.Column("active",sa.Boolean(),nullable=False),sa.Column("changed_by",sa.String(64),nullable=False),sa.Column("change_reason",sa.String(500),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("model_releases",sa.Column("id",sa.String(36),primary_key=True),sa.Column("name",sa.String(100),nullable=False),sa.Column("version",sa.String(64),nullable=False),sa.Column("model_sha256",sa.String(64),nullable=False,unique=True),sa.Column("training_dataset_version",sa.String(64),nullable=False),sa.Column("test_dataset_version",sa.String(64),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("automated_tests",sa.JSON(),nullable=False),sa.Column("comparison_result",sa.JSON(),nullable=False),sa.Column("approver",sa.String(64),nullable=True),sa.Column("approval_reason",sa.String(500),nullable=True),sa.Column("rollback_model_id",sa.String(36),nullable=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("operational_capas",sa.Column("id",sa.String(36),primary_key=True),sa.Column("error_type",sa.String(64),nullable=False),sa.Column("occurrence_count",sa.Integer(),nullable=False),sa.Column("model_version",sa.String(64),nullable=False),sa.Column("dataset_version",sa.String(64),nullable=False),sa.Column("analysis_ids",sa.JSON(),nullable=False),sa.Column("root_cause",sa.Text(),nullable=False),sa.Column("corrective_action",sa.Text(),nullable=False),sa.Column("preventive_action",sa.Text(),nullable=False),sa.Column("owner",sa.String(64),nullable=False),sa.Column("due_date",sa.String(16),nullable=True),sa.Column("effectiveness_check",sa.Text(),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("approved_by",sa.String(64),nullable=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("error_occurrences",sa.Column("id",sa.String(36),primary_key=True),sa.Column("error_type",sa.String(64),nullable=False),sa.Column("analysis_id",sa.String(36),nullable=True),sa.Column("model_version",sa.String(64),nullable=False),sa.Column("dataset_version",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
def downgrade():
    for table in ("error_occurrences","operational_capas","model_releases","review_priority_rules","study_analyses"):op.drop_table(table)
