"""validation, reproducibility, recovery and audit records"""
from alembic import op
import sqlalchemy as sa
revision="0010_validation";down_revision="0009_operations";branch_labels=None;depends_on=None
def upgrade():
    op.create_table("analysis_provenance",sa.Column("analysis_id",sa.String(36),primary_key=True),sa.Column("input_sha256",sa.String(64),nullable=False),sa.Column("manifest",sa.JSON(),nullable=False),sa.Column("raw_input_retained",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("test_requirements",sa.Column("id",sa.String(36),primary_key=True),sa.Column("requirement_id",sa.String(64),nullable=False,unique=True),sa.Column("risk_ids",sa.JSON(),nullable=False),sa.Column("title",sa.String(200),nullable=False))
    op.create_table("test_scenarios",sa.Column("id",sa.String(36),primary_key=True),sa.Column("test_id",sa.String(64),nullable=False,unique=True),sa.Column("requirement_id",sa.String(64),nullable=False),sa.Column("risk_ids",sa.JSON(),nullable=False),sa.Column("scenario_type",sa.String(32),nullable=False),sa.Column("preconditions",sa.Text(),nullable=False),sa.Column("input_data",sa.JSON(),nullable=False),sa.Column("steps",sa.JSON(),nullable=False),sa.Column("expected_result",sa.Text(),nullable=False))
    op.create_table("test_executions",sa.Column("id",sa.String(36),primary_key=True),sa.Column("scenario_id",sa.String(36),nullable=False),sa.Column("actual_result",sa.Text(),nullable=False),sa.Column("status",sa.String(16),nullable=False),sa.Column("tester",sa.String(64),nullable=False),sa.Column("retest_of",sa.String(36),nullable=True),sa.Column("executed_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("test_evidence",sa.Column("id",sa.String(36),primary_key=True),sa.Column("execution_id",sa.String(36),nullable=False),sa.Column("filename",sa.String(200),nullable=False),sa.Column("sha256",sa.String(64),nullable=False),sa.Column("storage_status",sa.String(32),nullable=False))
    op.create_table("defect_records",sa.Column("id",sa.String(36),primary_key=True),sa.Column("execution_id",sa.String(36),nullable=False),sa.Column("summary",sa.String(300),nullable=False),sa.Column("status",sa.String(32),nullable=False))
    op.create_table("annotation_records",sa.Column("id",sa.String(36),primary_key=True),sa.Column("anonymous_image_hash",sa.String(64),nullable=False),sa.Column("first_review",sa.JSON(),nullable=False),sa.Column("second_review",sa.JSON(),nullable=True),sa.Column("adjudication",sa.JSON(),nullable=True),sa.Column("final_label",sa.JSON(),nullable=True),sa.Column("status",sa.String(32),nullable=False),sa.Column("history",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("recovery_jobs",sa.Column("id",sa.String(36),primary_key=True),sa.Column("idempotency_key",sa.String(100),nullable=False,unique=True),sa.Column("analysis_id",sa.String(36),nullable=True),sa.Column("status",sa.String(32),nullable=False),sa.Column("attempts",sa.Integer(),nullable=False),sa.Column("max_attempts",sa.Integer(),nullable=False),sa.Column("next_retry_seconds",sa.Integer(),nullable=False),sa.Column("failure_reason",sa.String(500),nullable=True),sa.Column("model_version",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("audit_packages",sa.Column("id",sa.String(36),primary_key=True),sa.Column("created_by_role",sa.String(32),nullable=False),sa.Column("manifest",sa.JSON(),nullable=False),sa.Column("payload_base64",sa.Text(),nullable=False),sa.Column("package_sha256",sa.String(64),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("security_events",sa.Column("id",sa.String(36),primary_key=True),sa.Column("event_type",sa.String(64),nullable=False),sa.Column("request_id",sa.String(64),nullable=False),sa.Column("details",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
def downgrade():
    for table in ("security_events","audit_packages","recovery_jobs","annotation_records","defect_records","test_evidence","test_executions","test_scenarios","test_requirements","analysis_provenance"):op.drop_table(table)
