"""sLLM, Qdrant knowledge governance and grounded agent events"""
from alembic import op
import sqlalchemy as sa
revision="0011_sllm_qdrant";down_revision="0010_validation";branch_labels=None;depends_on=None
def upgrade():
    op.create_table("knowledge_documents",sa.Column("id",sa.String(36),primary_key=True),sa.Column("document_id",sa.String(80),unique=True,nullable=False),sa.Column("title",sa.String(200),nullable=False),sa.Column("document_type",sa.String(40),nullable=False),sa.Column("institution_id",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("knowledge_document_versions",sa.Column("id",sa.String(36),primary_key=True),sa.Column("document_id",sa.String(80),nullable=False),sa.Column("version",sa.String(32),nullable=False),sa.Column("approval_status",sa.String(32),nullable=False),sa.Column("effective_date",sa.String(16),nullable=False),sa.Column("expires_at",sa.String(32),nullable=True),sa.Column("allowed_roles",sa.JSON(),nullable=False),sa.Column("content_hash",sa.String(64),nullable=False),sa.Column("search_enabled",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("knowledge_chunks",sa.Column("id",sa.String(36),primary_key=True),sa.Column("document_id",sa.String(80),nullable=False),sa.Column("version",sa.String(32),nullable=False),sa.Column("chunk_id",sa.String(140),unique=True,nullable=False),sa.Column("qdrant_point_id",sa.String(64),nullable=True),sa.Column("content_hash",sa.String(64),nullable=False),sa.Column("embedding_model",sa.String(120),nullable=False),sa.Column("section",sa.String(160),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("knowledge_index_runs",sa.Column("id",sa.String(36),primary_key=True),sa.Column("status",sa.String(32),nullable=False),sa.Column("indexed_count",sa.Integer(),nullable=False),sa.Column("skipped_count",sa.Integer(),nullable=False),sa.Column("failed_documents",sa.JSON(),nullable=False),sa.Column("retrieval_mode",sa.String(32),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("agent_conversations",sa.Column("id",sa.String(36),primary_key=True),sa.Column("anonymous_user_id",sa.String(64),nullable=False),sa.Column("institution_id",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("agent_messages",sa.Column("id",sa.String(36),primary_key=True),sa.Column("conversation_id",sa.String(36),nullable=False),sa.Column("role",sa.String(16),nullable=False),sa.Column("masked_content",sa.Text(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("agent_retrieval_events",sa.Column("id",sa.String(36),primary_key=True),sa.Column("run_id",sa.String(36),nullable=False),sa.Column("document_id",sa.String(80),nullable=False),sa.Column("chunk_id",sa.String(140),nullable=False),sa.Column("bm25_rank",sa.Integer(),nullable=True),sa.Column("vector_rank",sa.Integer(),nullable=True),sa.Column("rrf_score",sa.Float(),nullable=False),sa.Column("selected",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("llm_inference_events",sa.Column("id",sa.String(36),primary_key=True),sa.Column("run_id",sa.String(36),nullable=False),sa.Column("provider",sa.String(32),nullable=False),sa.Column("model_name",sa.String(120),nullable=False),sa.Column("model_version",sa.String(120),nullable=False),sa.Column("prompt_template_version",sa.String(32),nullable=False),sa.Column("prompt_tokens",sa.Integer(),nullable=False),sa.Column("completion_tokens",sa.Integer(),nullable=False),sa.Column("latency_ms",sa.Float(),nullable=False),sa.Column("finish_reason",sa.String(32),nullable=False),sa.Column("dummy_mode",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
def downgrade():
    for table in ("llm_inference_events","agent_retrieval_events","agent_messages","agent_conversations","knowledge_index_runs","knowledge_chunks","knowledge_document_versions","knowledge_documents"):op.drop_table(table)
