"""integrated consistency validation records"""
from alembic import op
import sqlalchemy as sa
revision="0012_consistency";down_revision="0011_sllm_qdrant";branch_labels=None;depends_on=None
def upgrade():
    op.create_table("consistency_validation_runs",sa.Column("id",sa.String(36),primary_key=True),sa.Column("scope",sa.String(40),nullable=False),sa.Column("target_type",sa.String(40),nullable=False),sa.Column("target_id",sa.String(80),nullable=True),sa.Column("rule_engine_version",sa.String(32),nullable=False),sa.Column("summary",sa.JSON(),nullable=False),sa.Column("high_risk_block",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("consistency_findings",sa.Column("id",sa.String(36),primary_key=True),sa.Column("validation_run_id",sa.String(36),nullable=False),sa.Column("rule_id",sa.String(32),nullable=False),sa.Column("rule_version",sa.String(16),nullable=False),sa.Column("category",sa.String(40),nullable=False),sa.Column("target_resource",sa.String(160),nullable=False),sa.Column("expected",sa.JSON(),nullable=True),sa.Column("actual",sa.JSON(),nullable=True),sa.Column("status",sa.String(32),nullable=False),sa.Column("severity",sa.String(16),nullable=False),sa.Column("message",sa.Text(),nullable=False),sa.Column("automatic_action",sa.String(64),nullable=False),sa.Column("assigned_role",sa.String(32),nullable=True),sa.Column("resolved",sa.Boolean(),nullable=False),sa.Column("validation_type",sa.String(32),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("consistency_evidence",sa.Column("id",sa.String(36),primary_key=True),sa.Column("finding_id",sa.String(36),nullable=False),sa.Column("source_type",sa.String(40),nullable=False),sa.Column("source_id",sa.String(120),nullable=False),sa.Column("field",sa.String(120),nullable=False),sa.Column("value_hash",sa.String(64),nullable=True))
    op.create_table("consistency_rule_versions",sa.Column("id",sa.String(36),primary_key=True),sa.Column("rule_id",sa.String(32),nullable=False),sa.Column("version",sa.String(16),nullable=False),sa.Column("definition_hash",sa.String(64),nullable=False),sa.Column("active",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("consistency_resolutions",sa.Column("id",sa.String(36),primary_key=True),sa.Column("finding_id",sa.String(36),nullable=False),sa.Column("assigned_role",sa.String(32),nullable=False),sa.Column("comment",sa.Text(),nullable=False),sa.Column("resolution_evidence",sa.JSON(),nullable=False),sa.Column("change_reason",sa.String(500),nullable=False),sa.Column("resolved",sa.Boolean(),nullable=False),sa.Column("resolved_by",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
def downgrade():
    for table in ("consistency_resolutions","consistency_rule_versions","consistency_evidence","consistency_findings","consistency_validation_runs"):op.drop_table(table)
