"""phase27 model monitoring and drift"""
from alembic import op
import sqlalchemy as sa
revision="0013_monitoring_drift";down_revision="0012_consistency";branch_labels=None;depends_on=None
def upgrade():
    def common():return [sa.Column("id",sa.String(36),primary_key=True),sa.Column("model_version",sa.String(64),nullable=False),sa.Column("dataset_version",sa.String(64),nullable=False)]
    op.create_table("monitoring_snapshots",*common(),sa.Column("institution_id",sa.String(64),nullable=False),sa.Column("window_start",sa.DateTime(timezone=True),nullable=False),sa.Column("window_end",sa.DateTime(timezone=True),nullable=False),sa.Column("sample_size",sa.Integer(),nullable=False),sa.Column("metrics",sa.JSON(),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("drift_baselines",*common(),sa.Column("institution_id",sa.String(64),nullable=False),sa.Column("sample_size",sa.Integer(),nullable=False),sa.Column("metrics",sa.JSON(),nullable=False),sa.Column("approved_by_role",sa.String(32),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("drift_evaluations",*common(),sa.Column("baseline_id",sa.String(36),nullable=False),sa.Column("snapshot_id",sa.String(36),nullable=False),sa.Column("institution_id",sa.String(64),nullable=False),sa.Column("window_start",sa.DateTime(timezone=True),nullable=False),sa.Column("window_end",sa.DateTime(timezone=True),nullable=False),sa.Column("sample_size",sa.Integer(),nullable=False),sa.Column("drift_scores",sa.JSON(),nullable=False),sa.Column("severity",sa.String(32),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("evidence",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("monitoring_alerts",sa.Column("id",sa.String(36),primary_key=True),sa.Column("evaluation_id",sa.String(36),nullable=False),sa.Column("alert_type",sa.String(64),nullable=False),sa.Column("severity",sa.String(32),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("assigned_role",sa.String(32),nullable=False),sa.Column("change_reason",sa.String(500),nullable=False),sa.Column("evidence",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("resolved_at",sa.DateTime(timezone=True),nullable=True))
    op.create_table("model_performance_windows",*common(),sa.Column("window_start",sa.DateTime(timezone=True),nullable=False),sa.Column("window_end",sa.DateTime(timezone=True),nullable=False),sa.Column("sample_size",sa.Integer(),nullable=False),sa.Column("metrics",sa.JSON(),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("release_block_decisions",sa.Column("id",sa.String(36),primary_key=True),sa.Column("release_id",sa.String(36),nullable=False),sa.Column("model_version",sa.String(64),nullable=False),sa.Column("dataset_version",sa.String(64),nullable=False),sa.Column("blocked",sa.Boolean(),nullable=False),sa.Column("reason_codes",sa.JSON(),nullable=False),sa.Column("evidence",sa.JSON(),nullable=False),sa.Column("required_actions",sa.JSON(),nullable=False),sa.Column("assigned_role",sa.String(32),nullable=False),sa.Column("evaluated_at",sa.DateTime(timezone=True),nullable=False))
def downgrade():
    for table in ("release_block_decisions","model_performance_windows","monitoring_alerts","drift_evaluations","drift_baselines","monitoring_snapshots"):op.drop_table(table)
