"""phase28 modelops validation deployment"""
from alembic import op
import sqlalchemy as sa
revision="0014_modelops";down_revision="0013_monitoring_drift";branch_labels=None;depends_on=None
def upgrade():
    for name,type_,nullable,default in (("specification",sa.JSON(),False,"{}"),("registered_by",sa.String(64),False,"legacy"),("approved_by",sa.String(64),True,None),("deployed_by",sa.String(64),True,None)):
        op.add_column("model_releases",sa.Column(name,type_,nullable=nullable,server_default=default))
    op.create_table("model_artifacts",sa.Column("id",sa.String(36),primary_key=True),sa.Column("model_release_id",sa.String(36),nullable=False),sa.Column("filename",sa.String(200),nullable=False),sa.Column("format",sa.String(24),nullable=False),sa.Column("size_bytes",sa.Integer(),nullable=False),sa.Column("sha256",sa.String(64),nullable=False,unique=True),sa.Column("storage_uri",sa.String(500)),sa.Column("storage_status",sa.String(48),nullable=False),sa.Column("malware_scan_status",sa.String(40),nullable=False),sa.Column("signature_status",sa.String(40),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("model_validation_runs",sa.Column("id",sa.String(36),primary_key=True),sa.Column("model_release_id",sa.String(36),nullable=False),sa.Column("dataset_version",sa.String(64),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("validation_type",sa.String(32),nullable=False),sa.Column("environment",sa.String(64),nullable=False),sa.Column("seed",sa.Integer(),nullable=False),sa.Column("started_at",sa.DateTime(timezone=True),nullable=False),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.Column("requested_by",sa.String(64),nullable=False),sa.Column("idempotency_key",sa.String(100),nullable=False,unique=True),sa.Column("policy_id",sa.String(36)),sa.Column("retest_of",sa.String(36)),sa.Column("error_code",sa.String(64)),sa.Column("error_message",sa.String(500)))
    op.create_table("model_validation_metrics",sa.Column("id",sa.String(36),primary_key=True),sa.Column("validation_run_id",sa.String(36),nullable=False),sa.Column("metric_name",sa.String(64),nullable=False),sa.Column("anatomical_region",sa.String(64)),sa.Column("finding_code",sa.String(64)),sa.Column("subgroup",sa.String(100)),sa.Column("value",sa.Float()),sa.Column("threshold",sa.Float()),sa.Column("comparison_operator",sa.String(8),nullable=False),sa.Column("passed",sa.Boolean()),sa.Column("sample_size",sa.Integer(),nullable=False),sa.Column("status",sa.String(32),nullable=False))
    op.create_table("model_approvals",sa.Column("id",sa.String(36),primary_key=True),sa.Column("model_release_id",sa.String(36),nullable=False),sa.Column("decision",sa.String(24),nullable=False),sa.Column("approver_id",sa.String(64),nullable=False),sa.Column("approver_role",sa.String(32),nullable=False),sa.Column("reason",sa.String(500),nullable=False),sa.Column("validation_run_id",sa.String(36)),sa.Column("consistency_run_id",sa.String(36)),sa.Column("monitoring_gate_id",sa.String(36)),sa.Column("signature_meaning",sa.String(200),nullable=False),sa.Column("approved_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("deployment_records",sa.Column("id",sa.String(36),primary_key=True),sa.Column("model_release_id",sa.String(36),nullable=False),sa.Column("environment",sa.String(64),nullable=False),sa.Column("deployment_strategy",sa.String(24),nullable=False),sa.Column("previous_model_release_id",sa.String(36)),sa.Column("status",sa.String(32),nullable=False),sa.Column("deployed_by",sa.String(64),nullable=False),sa.Column("started_at",sa.DateTime(timezone=True),nullable=False),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.Column("rollback_available",sa.Boolean(),nullable=False),sa.Column("rollback_reason",sa.String(500)),sa.Column("release_gate_result",sa.JSON(),nullable=False))
    op.create_table("model_transition_events",sa.Column("id",sa.String(36),primary_key=True),sa.Column("model_release_id",sa.String(36),nullable=False),sa.Column("from_status",sa.String(32),nullable=False),sa.Column("to_status",sa.String(32),nullable=False),sa.Column("actor_id",sa.String(64),nullable=False),sa.Column("actor_role",sa.String(32),nullable=False),sa.Column("reason",sa.String(500),nullable=False),sa.Column("request_id",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("model_inference_bindings",sa.Column("id",sa.String(36),primary_key=True),sa.Column("environment",sa.String(64),nullable=False),sa.Column("model_release_id",sa.String(36),nullable=False),sa.Column("active",sa.Boolean(),nullable=False),sa.Column("traffic_percentage",sa.Float(),nullable=False),sa.Column("updated_by",sa.String(64),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("validation_policies",sa.Column("id",sa.String(36),primary_key=True),sa.Column("policy_id",sa.String(64),nullable=False),sa.Column("version",sa.String(32),nullable=False),sa.Column("target_region",sa.String(64)),sa.Column("target_finding",sa.String(64)),sa.Column("metric_thresholds",sa.JSON(),nullable=False),sa.Column("minimum_sample_size",sa.Integer(),nullable=False),sa.Column("robustness_thresholds",sa.JSON(),nullable=False),sa.Column("fairness_thresholds",sa.JSON(),nullable=False),sa.Column("latency_thresholds",sa.JSON(),nullable=False),sa.Column("active",sa.Boolean(),nullable=False),sa.Column("created_by",sa.String(64),nullable=False),sa.Column("approved_by",sa.String(64)),sa.Column("approved_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
def downgrade():
    for table in ("validation_policies","model_inference_bindings","model_transition_events","deployment_records","model_approvals","model_validation_metrics","model_validation_runs","model_artifacts"):op.drop_table(table)
    for name in ("deployed_by","approved_by","registered_by","specification"):op.drop_column("model_releases",name)
