import { useEffect, useState } from 'react';
import { Activity, AlertTriangle, BarChart3, BrainCircuit, CheckCircle2, Clock3, FileImage, History, Info, LayoutDashboard, Menu, ShieldCheck, UploadCloud, X } from 'lucide-react';
type Top={class:string;display_name:string;confidence:number};
type Prediction={prediction_id:string;anatomical_region:string;display_name:string;confidence:number;top_predictions:Top[];laterality:string;view_position:string;review_required:boolean;review_reasons:string[];model_version:string;dummy_mode:boolean;processing_time_ms:number};
const api=import.meta.env.VITE_API_URL||'';
const reason:Record<string,string>={LOW_CONFIDENCE:'최고 신뢰도가 자동 분류 기준보다 낮습니다',AMBIGUOUS_PREDICTION:'상위 예측 간 확률 차이가 작습니다',LATERALITY_UNKNOWN:'좌우 방향을 확인할 수 없습니다',VIEW_UNKNOWN:'촬영 방향을 확인할 수 없습니다',METADATA_CONFLICT:'DICOM 메타데이터와 AI 결과가 다릅니다'};
const nav=[['dashboard','대시보드',LayoutDashboard],['upload','X-ray 업로드',UploadCloud],['review','검토 대기',Clock3],['history','분석 이력',History],['stats','성능 통계',BarChart3],['system','시스템 정보',Info]] as const;
export default function App(){
 const [page,setPage]=useState('upload'),[file,setFile]=useState<File|null>(null),[drag,setDrag]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<Prediction|null>(null),[history,setHistory]=useState<Prediction[]>([]),[open,setOpen]=useState(false);
 const load=()=>{fetch(`${api}/api/predictions`).then(r=>r.ok?r.json():[]).then(setHistory).catch(()=>setHistory([]))}; useEffect(()=>{load()},[]);
 const reviewOne=async(id:string,region:string)=>{const comment=window.prompt('검토 의견을 입력하세요','영상과 메타데이터를 확인함')??'';const r=await fetch(`${api}/api/predictions/${id}/review`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({corrected_region:region,comment})});if(!r.ok){setError('검토 결과 저장에 실패했습니다.');return}load()};
 const submit=async()=>{if(!file)return;setBusy(true);setError('');try{const form=new FormData();form.append('file',file);const r=await fetch(`${api}/api/predictions`,{method:'POST',body:form});const d=await r.json();if(!r.ok)throw new Error(d.error?.message||d.detail||'분석에 실패했습니다.');setResult(d);setPage('result');load()}catch(e){setError(e instanceof Error?e.message:'오류가 발생했습니다.')}finally{setBusy(false)}};
 return <div className="app"><aside className={open?'open':''}><div className="brand"><div className="logo"><BrainCircuit/></div><div><b>X-Ray Router</b><span>ANATOMICAL AI</span></div><button className="close" onClick={()=>setOpen(false)}><X/></button></div><nav>{nav.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setOpen(false)}}><Icon/>{label}{id==='review'&&history.filter(x=>x.review_required).length>0&&<em>{history.filter(x=>x.review_required).length}</em>}</button>)}</nav><div className="privacy"><ShieldCheck/><b>개인정보 보호 설계</b><p>원본 영상은 분석 후 보관하지 않으며 환자 식별정보를 저장하지 않습니다.</p></div></aside>
 <main><header><button className="menu" onClick={()=>setOpen(true)}><Menu/></button><div><h1>{page==='upload'?'X-ray 영상 분석':page==='result'?'분석 결과':page==='review'?'검토 대기 목록':page==='history'?'분석 이력':page==='stats'?'성능 통계':page==='system'?'시스템 및 모델 정보':'대시보드'}</h1><p>AI 기반 해부학적 촬영 부위 분류 및 라우팅</p></div><span className="status"><i/>더미 모델 온라인</span></header>
 <section className="notice"><AlertTriangle/><div><b>연구·교육용 보조 시스템</b><p>본 결과는 의료 진단이 아니며, 의료진의 최종 판단을 대체하지 않습니다.</p></div></section>
 {page==='upload'&&<div className="upload-layout"><div className="card upload-card"><div className="card-title"><span><UploadCloud/></span><div><h2>영상 업로드</h2><p>DICOM, PNG, JPG 파일을 안전하게 분석합니다.</p></div></div><label className={`drop ${drag?'drag':''}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);setFile(e.dataTransfer.files[0]);setError('')}}><input type="file" accept=".dcm,.png,.jpg,.jpeg" onChange={e=>{setFile(e.target.files?.[0]||null);setError('')}}/><div className="drop-icon"><FileImage/></div>{file?<><b>{file.name}</b><p>{(file.size/1024/1024).toFixed(2)} MB</p></>:<><b>파일을 이곳에 끌어다 놓으세요</b><p>또는 클릭하여 파일 선택</p><small>DICOM · PNG · JPG · JPEG / 최대 20 MB</small></>}</label>{error&&<div className="error"><AlertTriangle/>{error}</div>}<button className="primary" disabled={!file||busy} onClick={submit}>{busy?<><span className="spinner"/>영상 분석 중...</>:<><Activity/>AI 분석 시작</>}</button></div><div className="side-stack"><div className="card info-card"><h3>분석 항목</h3>{['8개 해부학적 촬영 부위','예측 신뢰도 및 상위 3개 결과','좌우·촬영 방향 메타데이터','불확실한 결과 자동 검토 요청'].map(x=><p key={x}><CheckCircle2/>{x}</p>)}</div><div className="card warning"><h3><ShieldCheck/>업로드 전 확인</h3><p>환자 식별정보가 포함될 수 있습니다. 시스템은 분석에 필요한 픽셀과 제한된 메타데이터만 처리하며 원본을 영구 저장하지 않습니다.</p></div></div></div>}
 {page==='result'&&result&&<Result result={result} onBack={()=>setPage('upload')}/>} {page==='history'&&<Table rows={history} onReview={reviewOne}/>} {page==='review'&&<Table rows={history.filter(x=>x.review_required)} onReview={reviewOne}/>} {page==='dashboard'&&<Dashboard rows={history} onUpload={()=>setPage('upload')}/>} {page==='stats'&&<Stats rows={history}/>} {page==='system'&&<System/>}
 </main></div>}
function Result({result,onBack}:{result:Prediction,onBack:()=>void}){return <div className="result-grid"><div className="card hero-result"><div className="result-head"><span className={result.review_required?'review-badge':'ok-badge'}>{result.review_required?<><AlertTriangle/>검토 필요</>:<><CheckCircle2/>자동 분류 완료</>}</span><small>{result.processing_time_ms} ms · {result.model_version}</small></div><p>예측 촬영 부위</p><h2>{result.display_name}</h2><b className="code">{result.anatomical_region}</b><div className="gauge"><span style={{width:`${result.confidence*100}%`}}/></div><strong>{(result.confidence*100).toFixed(1)}% <small>신뢰도</small></strong><div className="meta"><div><span>좌우 방향</span><b>{result.laterality}</b></div><div><span>촬영 방향</span><b>{result.view_position}</b></div></div></div><div className="card"><h3>상위 예측 결과</h3>{result.top_predictions.map((x,i)=><div className="bar" key={x.class}><div><b>{i+1}. {x.display_name}</b><span>{(x.confidence*100).toFixed(1)}%</span></div><i><span style={{width:`${x.confidence*100}%`}}/></i></div>)}</div>{result.review_required&&<div className="card reasons"><h3><AlertTriangle/>검토가 필요한 이유</h3>{result.review_reasons.map(x=><p key={x}>• {reason[x]||x}</p>)}</div>}<div className="actions"><button onClick={onBack}>새 영상 분석</button></div></div>}
function Table({rows,onReview}:{rows:Prediction[];onReview:(id:string,region:string)=>void}){return <div className="card table-card">{rows.length?<table><thead><tr><th>촬영 부위</th><th>신뢰도</th><th>방향</th><th>상태</th><th>모델</th><th>작업</th></tr></thead><tbody>{rows.map(x=><tr key={x.prediction_id}><td><b>{x.display_name}</b><small>{x.anatomical_region}</small></td><td>{(x.confidence*100).toFixed(1)}%</td><td>{x.laterality} · {x.view_position}</td><td><span className={x.review_required?'pill red':'pill'}>{x.review_required?'검토 필요':'완료'}</span></td><td>{x.model_version}</td><td>{x.review_required&&<button className="review-btn" onClick={()=>onReview(x.prediction_id,x.anatomical_region)}>결과 확정</button>}</td></tr>)}</tbody></table>:<div className="empty"><History/><h3>표시할 분석 결과가 없습니다</h3><p>영상을 업로드하면 이곳에서 확인할 수 있습니다.</p></div>}</div>}
function Dashboard({rows,onUpload}:{rows:Prediction[];onUpload:()=>void}){const avg=rows.reduce((a,x)=>a+x.confidence,0)/(rows.length||1);return <><div className="metric-grid"><Metric label="전체 처리" value={`${rows.length}건`} icon={FileImage}/><Metric label="평균 신뢰도" value={`${(avg*100).toFixed(1)}%`} icon={Activity}/><Metric label="검토 대기" value={`${rows.filter(x=>x.review_required).length}건`} icon={Clock3}/></div><div className="card empty"><BrainCircuit/><h2>새 X-ray 영상을 분석해보세요</h2><p>모델 가중치 없이도 재현 가능한 더미 모드로 전체 워크플로를 시연할 수 있습니다.</p><button className="primary short" onClick={onUpload}><UploadCloud/>영상 업로드</button></div></>}
function Metric({label,value,icon:Icon}:{label:string;value:string;icon:any}){return <div className="card metric"><span><Icon/></span><div><p>{label}</p><b>{value}</b></div></div>}
function Stats({rows}:{rows:Prediction[]}){return <div className="card"><h2>운영 통계</h2><p className="muted">실제 성능 지표는 검토 정답 데이터가 축적된 후 표시됩니다.</p><div className="stats-bars">{Object.entries(rows.reduce<Record<string,number>>((a,x)=>(a[x.display_name]=(a[x.display_name]||0)+1,a),{})).map(([k,v])=><div className="bar" key={k}><div><b>{k}</b><span>{v}건</span></div><i><span style={{width:`${Math.min(100,v/Math.max(1,rows.length)*100)}%`}}/></i></div>)}</div></div>}
function System(){return <div className="card system"><BrainCircuit/><h2>dummy-v1</h2><span className="pill">DETERMINISTIC DUMMY</span><p>동일한 파일은 항상 동일한 결과를 반환합니다. 현재 결과는 학습된 의료 AI 모델의 성능을 나타내지 않습니다.</p><dl><div><dt>지원 클래스</dt><dd>8개</dd></div><div><dt>실행 장치</dt><dd>CPU</dd></div><div><dt>용도</dt><dd>연구·교육용</dd></div></dl></div>}

