import {useEffect,useState} from 'react';
import {AlertTriangle,CheckCircle2,RotateCcw,ShieldCheck} from 'lucide-react';
import {apiFetch} from './api';
type Release={model_release_id:string;name:string;version:string;status:string;checkpoint_sha256:string|null;training_dataset_version:string;test_dataset_version:string;registered_by:string;approved_by?:string;specification?:Record<string,unknown>};
export default function ModelOpsCenter({baseUrl}:{baseUrl:string}){
 const [state,setState]=useState<'loading'|'empty'|'error'|'permission'|'success'>('loading'),[items,setItems]=useState<Release[]>([]),[selected,setSelected]=useState<Release|null>(null);
 const load=async()=>{setState('loading');try{const r=await apiFetch(`${baseUrl}/api/v1/model-releases`);if(r.status===403){setState('permission');return}if(!r.ok)throw new Error();const data=await r.json();setItems(data);setState(data.length?'success':'empty')}catch{setState('error')}};
 useEffect(()=>{load()},[]);
 if(state==='loading')return <div className="card" role="status"><span className="spinner"/> 모델 생명주기를 불러오는 중입니다.</div>;
 if(state==='permission')return <div className="error" role="alert"><AlertTriangle/>ModelOps 조회 권한이 없습니다.</div>;
 if(state==='error')return <div className="error" role="alert"><AlertTriangle/>ModelOps 데이터를 불러오지 못했습니다.<button onClick={load}>다시 시도</button></div>;
 if(state==='empty')return <div className="card empty"><ShieldCheck/><h2>등록된 모델 릴리스가 없습니다</h2><p>실제 체크포인트를 임의로 생성하지 않습니다. ML 엔지니어가 검증할 모델을 등록하세요.</p></div>;
 return <div className="literacy"><section className="notice"><AlertTriangle/><div><b>내부 ModelOps 승인</b><p>이 상태는 규제기관 또는 임상 사용 승인이 아니며 의료진의 판단을 대체하지 않습니다.</p></div></section><div className="card table-card"><h2>ModelOps 관리센터</h2><table aria-label="모델 릴리스 목록"><thead><tr><th>모델</th><th>상태</th><th>체크포인트</th><th>데이터셋</th><th>등록자</th><th>작업</th></tr></thead><tbody>{items.map(x=><tr key={x.model_release_id}><td><b>{x.name}</b><small>{x.version}</small></td><td><span className={`mops-status ${x.status.toLowerCase()}`}>{x.status}</span></td><td>{x.checkpoint_sha256?`${x.checkpoint_sha256.slice(0,12)}…`:'NOT_VERIFIED'}</td><td>{x.training_dataset_version} / {x.test_dataset_version}</td><td>{x.registered_by}</td><td><button onClick={()=>setSelected(x)}>상세</button></td></tr>)}</tbody></table></div>{selected&&<div className="result-grid"><div className="card"><h2>{selected.name} {selected.version}</h2><p><b>Intended use:</b> {String(selected.specification?.intended_use||'미등록')}</p><p><b>Prohibited use:</b> {String(selected.specification?.prohibited_use||'미등록')}</p><p><b>검증 상태:</b> {selected.status.includes('FAILED')?'검증 실패':selected.status}</p><p><b>성능:</b> NOT_MEASURED는 통과로 간주하지 않습니다.</p></div><div className="card"><h2>승인·배포 제어</h2><p><CheckCircle2/> 등록자·승인자·배포자를 분리합니다.</p><p><ShieldCheck/> Release Gate와 체크포인트 해시가 일치해야 합니다.</p><button disabled={selected.status!=='APPROVAL_REQUIRED'}>승인 검토</button> <button disabled={selected.status!=='APPROVED'}>DEMO 배포</button><button disabled={selected.status!=='DEPLOYED'} aria-label="롤백 확인"><RotateCcw/>롤백</button></div></div>}</div>;
}
