import { useEffect, useState } from 'react';
import { apiFetch } from './api';
const colors:Record<string,string>={STABLE:'#16803c',WARNING:'#c15f00',CRITICAL:'#c62828',NOT_MEASURED:'#667085',INSUFFICIENT_DATA:'#1769aa',RELEASE_BLOCKED:'#7f1d1d'};
const show=(value:unknown,suffix='')=>value===null||value===undefined?'NOT_MEASURED':`${value}${suffix}`;
export default function MonitoringDashboard({baseUrl=''}:{baseUrl?:string}){
 const [state,setState]=useState<'loading'|'success'|'empty'|'error'|'permission'>('loading'),[data,setData]=useState<any>(null),[message,setMessage]=useState('');
 useEffect(()=>{apiFetch(`${baseUrl}/api/v1/monitoring/dashboard`).then(async r=>{if(r.status===403){setState('permission');return}if(!r.ok)throw new Error('모니터링 대시보드를 불러오지 못했습니다.');const body=await r.json();setData(body);setState(body.latest_snapshot?'success':'empty')}).catch(e=>{setMessage(e instanceof Error?e.message:'모니터링 오류');setState('error')})},[baseUrl]);
 if(state==='loading')return <div className="card" role="status">운영 지표를 불러오는 중입니다…</div>;
 if(state==='permission')return <div className="card error" role="alert">권한이 없습니다. ML_ENGINEER, QA_RA 또는 ADMIN 역할을 확인하세요.</div>;
 if(state==='error')return <div className="card error" role="alert">{message}</div>;
 if(state==='empty')return <div className="card"><h2>모델 운영 모니터링</h2><Status value="NOT_MEASURED"/><p>{data?.reason||'측정 가능한 운영 데이터가 없습니다.'}</p><p>빈 차트를 그리지 않으며 실제 임상 성능을 생성하지 않습니다.</p></div>;
 const snapshot=data.latest_snapshot,metrics=snapshot.metrics||{};
 return <div className="literacy"><div className="card"><h2>모델 운영 모니터링</h2><Status value={data.status}/><Status value={data.release_status}/><p>모델 {snapshot.model_version} · 데이터 {snapshot.dataset_version}</p><p>측정 기간 {snapshot.window_start} ~ {snapshot.window_end} · 표본 {snapshot.sample_size}건</p></div><div className="metric-grid">{[['총 분석',metrics.total_requests,'건'],['성공률',metrics.success_rate===undefined?null:(metrics.success_rate*100).toFixed(1),'%'],['P95',metrics.p95_latency_ms,' ms'],['OOD',metrics.ood_rate===undefined?null:(metrics.ood_rate*100).toFixed(1),'%'],['품질 REJECT',metrics.quality_reject_rate===undefined?null:(metrics.quality_reject_rate*100).toFixed(1),'%'],['검토 전환',metrics.review_rate===undefined?null:(metrics.review_rate*100).toFixed(1),'%'],['의료진 수정',metrics.correction_rate===undefined?null:(metrics.correction_rate*100).toFixed(1),'%'],['정합성 실패',metrics.consistency_failure_rate===undefined?null:(metrics.consistency_failure_rate*100).toFixed(1),'%']].map(([label,value,suffix])=><div className="card metric" key={String(label)}><p>{label}</p><b>{show(value,suffix as string)}</b></div>)}</div><div className="result-grid"><div className="card"><h3>부위별 분석 분포</h3>{Object.keys(metrics.region_distribution||{}).length?<table><tbody>{Object.entries(metrics.region_distribution).map(([k,v])=><tr key={k}><th>{k}</th><td>{String(v)}건</td></tr>)}</tbody></table>:<p>NOT_MEASURED — 부위별 표본이 없습니다.</p>}</div><div className="card"><h3>드리프트 경고</h3>{data.alerts.length?data.alerts.map((x:any)=><p key={x.alert_id}><Status value={x.severity}/> {x.type} · {x.status}</p>):<p>현재 미해결 경고가 없습니다.</p>}</div><div className="card"><h3>CAPA 후보</h3>{data.capa_candidates.length?data.capa_candidates.map((x:any)=><p key={x.capa_id}>{x.problem_type} · {x.occurrence_count}회 · <b>{x.status}</b></p>):<p>자동 생성된 CAPA 후보가 없습니다.</p>}</div></div><p><b>드리프트는 입력 분포 변화이며 실제 정답 라벨 없이 임상 성능 저하로 단정하지 않습니다.</b></p></div>;
}
function Status({value}:{value:string}){return <span className="pill" data-status={value} style={{backgroundColor:colors[value]||colors.NOT_MEASURED,color:'white',marginRight:8}}>{value}</span>}
