ALLOWED={"ROUTE_TO_REVIEW","BLOCK_AUTO_APPROVAL","BLOCK_MODEL_DEPLOYMENT","MARK_REPORT_REGENERATION_REQUIRED","DISABLE_DOCUMENT_SEARCH","NOTIFY_ADMIN","SCHEDULE_REVALIDATION","RELEASE_BLOCK","STARTUP_BLOCK","CONFIGURATION_CHANGE_REQUIRED","QA_RA_REVIEW","NONE"}
FORBIDDEN={"MODIFY_CLINICAL_RESULT","MODIFY_DICOM","APPROVE_MODEL","DEPLOY_MODEL","CLOSE_CAPA","APPROVE_DOCUMENT","MODIFY_QDRANT_CONTENT"}
ALLOWED.add("BLOCK_EXTERNAL_TRANSFER")
ALLOWED.update({'APPROVAL_BLOCK', 'DOCUMENT_DOWNLOAD_BLOCK'})
def validate_action(action):
    if action in FORBIDDEN:raise ValueError("금지된 자동 조치입니다.")
    return action in ALLOWED
