REGIONS = {
    "CHEST": "흉부", "ABDOMEN": "복부", "SPINE": "척추", "PELVIS": "골반",
    "SHOULDER_ARM": "어깨·팔", "HAND_WRIST": "손·손목", "KNEE": "무릎", "FOOT_ANKLE": "발·발목",
}
LATERALITIES = {"L": "LEFT", "R": "RIGHT", "B": "BILATERAL", "BOTH": "BILATERAL"}
VIEWS = {"AP": "AP", "PA": "PA", "LAT": "LATERAL", "LATERAL": "LATERAL", "OBL": "OBLIQUE", "OBLIQUE": "OBLIQUE"}

HIERARCHICAL_REGIONS = {
    "HEAD": ["SKULL"], "NECK": ["CERVICAL_SPINE"], "CHEST": [], "ABDOMEN": [],
    "SPINE": ["CERVICAL_SPINE", "THORACIC_SPINE", "LUMBAR_SPINE"],
    "PELVIS_HIP": ["PELVIS", "HIP"],
    "UPPER_EXTREMITY": ["SHOULDER", "HUMERUS", "ELBOW", "FOREARM", "WRIST", "HAND", "FINGER"],
    "LOWER_EXTREMITY": ["FEMUR", "KNEE", "LOWER_LEG", "ANKLE", "FOOT", "TOE"],
    "OTHER": [], "UNKNOWN": [],
}

